apiVersion: v1
kind: Service
metadata:
  name: triage-engine
  namespace: healthcare-triage-dev
  labels:
    app: triage-engine
    environment: dev
spec:
  type: ClusterIP
  selector:
    app: triage-engine
  ports:
    - name: http
      port: 8002
      targetPort: http
