apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: healthcare-triage-dev
  labels:
    app: auth-service
    environment: dev
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "8001"
spec:
  type: ClusterIP
  selector:
    app: auth-service
  ports:
    - name: http
      port: 8001
      targetPort: http
